name = "akuaby"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "91.192.81.154:2053"
UUID = "b59fe830-562c-4faf-b9aa-5758398889a2"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
